### ISSUE TITLE
Error datos 10/05/2020

### ISSUE THREAD

**Issue by hiramRV** [ncovgt2020/ncovgt2020#2]
Note una pequeña inconsistencia en los datos el día 10/05/2020 (Imagen 1). El número de casos recuperados se corrio una columna abajo y el de casos activos difiere de lo que publica el MSPAS (Imagen 2). 

Voy a corregirlo y crear una Pull request. 

![Img1](https://user-images.githubusercontent.com/65641167/85018375-502b9e00-b12a-11ea-9029-be96df3e46f6.jpg)
![Img2](https://user-images.githubusercontent.com/65641167/85018376-50c43480-b12a-11ea-858f-40863e56b9a4.jpg)

**Comment by ncovgt2020** [comment]
@hiram22 Gracias por notar el error. ¿Podrías por favor poner acá enlaces a la fuente del MSPAS donde viste el dato correcto? Es necesario dejar constancia de las fuentes para darle trazabilidad y confianza a la información. Cuando lo hagas, por favor actualiza el pull request con tus cambios para que podamos fusionarlo con los últimos datos actualizados.

**Comment by hiramRV** [comment]
Claro, la fuente primaria que uso son los archivos que suben en esta página: 

https://www.mspas.gob.gt/index.php/noticias/covid-19/casos

Al final te dejan descargar los datos y los actualizan día a día.

**Comment by ncovgt2020** [comment]
Gracias, por favor actualiza el pull request para hacer merge a master. Vamos a esperar que hagas el pull request antes de fusionar los cambios (que producirían conflictos con tu pull).

**Comment by hiramRV** [comment]
Cuando decis actualizar es colocar los datos al día de hoy, ¿verdad? Solo para tenerlo claro.

**Comment by ncovgt2020** [comment]
Con "actualizar" me refería sencillamente la cambio que ya realizaste. Ya fusionamos tu pull request. Te vamos a colocar como contributor :)

**Comment by hiramRV** [comment]
Entendido  Y gracias!
