### ISSUE TITLE
Datos repetidos

### ISSUE THREAD

**Issue by hiramRV** [ncovgt2020/ncovgt2020#6]
![image](https://user-images.githubusercontent.com/65641167/86279810-d9fe5100-bb97-11ea-8129-af80d8fe0d0c.png)

Aparentemente los datos de anteayer (29/06/2020) y hoy (30/06/2020) son los mismos (Solo las pruebas se actualizaron).

**Comment by ncovgt2020** [comment]
@hiram22  Gracias por notar el error. El problema fue que los datos para el 25 de junio no se habian ingresado y se copiaban los anteriores. Ya corregí el error.
